services:
    s4a_user.my_provider:
        class: Base\UserBundle\Security\Provider\MyProvider #Chemin vers le provider
        public: false
        arguments: ["@fos_user.user_manager"]
    
    base_user.registration.form.type:
        class: Base\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: base_user_registration }
