<?php

namespace Base\DiridarekBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AmisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmisRepository extends EntityRepository
{
}
